version: "3.2"

services:
  pynx584:
    container_name: pynx584
    image: kk7ds/pynx584
    build:
      context: .docker
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5007:5007
    network_mode: bridge
